/// Rhai-based scripting engine (MASTERPLAN §4.3, §11)
///
/// # Design
///
/// Scripts run synchronously on a blocking thread (`spawn_blocking`).  The
/// `SessionApi` object (the `s` in scripts) holds:
///   - a tokio mpsc write channel  → sends bytes to the remote connection
///   - a std::sync mpsc data channel → receives bytes from the connection
///   - a shared log buffer         → collects `s.log()` messages for the UI
///
/// Keeping the data channel as a *sync* mpsc lets `wait_for` block the script
/// thread without touching the async runtime.
use std::{
    collections::HashMap,
    path::PathBuf,
    sync::{Arc, Mutex},
    time::{Duration, Instant},
};

use regex::Regex;
use rhai::{Dynamic, Engine, EvalAltResult, Scope, AST};
use tokio::sync::mpsc as async_mpsc;

// ── SessionApi ────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ScriptCommand {
    Disconnect,
}

/// Inner mutable state shared between the API clone used by the script and
/// the holder in [`TabSession`].
pub struct SessionApiInner {
    pub buffer: String,
    pub vars: HashMap<String, String>,
    pub credentials: HashMap<String, String>,
    pub entry_name: String,
    pub log_buffer: Arc<Mutex<Vec<String>>>,
}

/// The `s` object available to every Rhai script hook.
///
/// Implements `Clone` (Rhai requirement) via `Arc<Mutex<_>>`.
#[derive(Clone)]
pub struct SessionApi {
    inner: Arc<Mutex<SessionApiInner>>,
    /// Forwards bytes typed / generated by the script to the remote.
    pub write_tx: async_mpsc::Sender<Vec<u8>>,
    /// Receives raw bytes from the remote (sync channel, safe to block on).
    data_rx: Arc<Mutex<std::sync::mpsc::Receiver<Vec<u8>>>>,
    /// Sends script control requests back to the session owner.
    control_tx: Option<async_mpsc::Sender<ScriptCommand>>,
}

impl SessionApi {
    pub fn new(
        entry_name: String,
        write_tx: async_mpsc::Sender<Vec<u8>>,
        data_rx: std::sync::mpsc::Receiver<Vec<u8>>,
        log_buffer: Arc<Mutex<Vec<String>>>,
    ) -> Self {
        Self::with_credentials(entry_name, write_tx, data_rx, log_buffer, HashMap::new())
    }

    pub fn with_credentials(
        entry_name: String,
        write_tx: async_mpsc::Sender<Vec<u8>>,
        data_rx: std::sync::mpsc::Receiver<Vec<u8>>,
        log_buffer: Arc<Mutex<Vec<String>>>,
        credentials: HashMap<String, String>,
    ) -> Self {
        Self {
            inner: Arc::new(Mutex::new(SessionApiInner {
                buffer: String::new(),
                vars: HashMap::new(),
                credentials,
                entry_name,
                log_buffer,
            })),
            write_tx,
            data_rx: Arc::new(Mutex::new(data_rx)),
            control_tx: None,
        }
    }

    pub fn with_credentials_and_control(
        entry_name: String,
        write_tx: async_mpsc::Sender<Vec<u8>>,
        data_rx: std::sync::mpsc::Receiver<Vec<u8>>,
        log_buffer: Arc<Mutex<Vec<String>>>,
        credentials: HashMap<String, String>,
        control_tx: async_mpsc::Sender<ScriptCommand>,
    ) -> Self {
        let mut api =
            Self::with_credentials(entry_name, write_tx, data_rx, log_buffer, credentials);
        api.control_tx = Some(control_tx);
        api
    }

    // ── Internal helpers (called by registered Rhai fns) ──────────────────────

    fn do_send(&mut self, bytes: Vec<u8>) {
        self.write_tx.blocking_send(bytes).ok();
    }

    fn do_wait_for(&mut self, pattern: &str, timeout_secs: f64) -> bool {
        let re = match Regex::new(pattern) {
            Ok(r) => r,
            Err(_) => return false,
        };
        let deadline = Instant::now() + Duration::from_secs_f64(timeout_secs.max(0.0));

        loop {
            // Check accumulated buffer.
            let Ok(inner) = self.inner.lock() else {
                return false;
            };
            if re.is_match(&inner.buffer) {
                return true;
            }
            drop(inner);

            let remaining = deadline.saturating_duration_since(Instant::now());
            if remaining.is_zero() {
                return false;
            }

            // Block the script thread waiting for more data (releases inner lock).
            let poll_dur = remaining.min(Duration::from_millis(50));
            let recv_result = match self.data_rx.lock() {
                Ok(rx) => rx.recv_timeout(poll_dur),
                Err(_) => return false,
            };
            match recv_result {
                Ok(bytes) => {
                    if let Ok(s) = std::str::from_utf8(&bytes) {
                        let Ok(mut inner) = self.inner.lock() else {
                            return false;
                        };
                        inner.buffer.push_str(s);
                    }
                }
                Err(std::sync::mpsc::RecvTimeoutError::Timeout) => continue,
                Err(std::sync::mpsc::RecvTimeoutError::Disconnected) => return false,
            }
        }
    }

    fn do_log(&mut self, msg: String) {
        let Ok(inner) = self.inner.lock() else {
            return;
        };
        let log_buffer = Arc::clone(&inner.log_buffer);
        drop(inner);

        if let Ok(mut buffer) = log_buffer.lock() {
            buffer.push(msg);
        };
    }

    fn do_set_var(&mut self, key: String, val: String) {
        if let Ok(mut inner) = self.inner.lock() {
            inner.vars.insert(key, val);
        }
    }

    fn do_get_var(&mut self, key: String) -> String {
        self.inner
            .lock()
            .ok()
            .and_then(|inner| inner.vars.get(&key).cloned())
            .unwrap_or_default()
    }

    fn do_entry_name(&mut self) -> String {
        self.inner
            .lock()
            .map(|inner| inner.entry_name.clone())
            .unwrap_or_default()
    }

    fn do_credential(&mut self, key: String) -> String {
        self.inner
            .lock()
            .ok()
            .and_then(|inner| inner.credentials.get(&key.to_lowercase()).cloned())
            .unwrap_or_default()
    }

    fn do_disconnect(&mut self) {
        if let Some(tx) = &self.control_tx {
            tx.blocking_send(ScriptCommand::Disconnect).ok();
        }
    }
}

// ── Script storage ────────────────────────────────────────────────────────────

/// A loaded script with its content and origin path.
#[derive(Debug, Clone)]
pub struct Script {
    pub name: String,
    pub path: PathBuf,
    pub content: String,
}

/// Manages script files under `~/.config/waystone-comm/scripts/`.
#[derive(Debug, Clone)]
pub struct ScriptStore {
    pub base_dir: PathBuf,
}

impl ScriptStore {
    pub fn default_path() -> PathBuf {
        dirs::config_dir()
            .unwrap_or_else(|| PathBuf::from("~/.config"))
            .join("waystone-comm")
            .join("scripts")
    }

    pub fn new(base_dir: impl Into<PathBuf>) -> Self {
        Self {
            base_dir: base_dir.into(),
        }
    }

    pub fn new_default() -> Self {
        Self::new(Self::default_path())
    }

    /// Load the on_connect script for a named directory entry (if any).
    /// Looks for `entries/<name>.rhai`.
    pub fn entry_script(&self, entry_name: &str) -> Option<Script> {
        self.load_script(self.entry_script_path(entry_name))
    }

    /// Return the `entries/<name>.rhai` path for a directory entry.
    pub fn entry_script_path(&self, entry_name: &str) -> PathBuf {
        let safe = sanitise_name(entry_name);
        self.base_dir.join("entries").join(format!("{safe}.rhai"))
    }

    /// Load a named script from the script store.
    ///
    /// Search order is `global/`, `entries/`, then `library/`.
    pub fn named_script(&self, name: &str) -> Option<Script> {
        let safe = sanitise_name(name);
        for subdir in &["global", "entries", "library"] {
            let path = self.base_dir.join(subdir).join(format!("{safe}.rhai"));
            if let Some(script) = self.load_script(path) {
                return Some(script);
            }
        }
        None
    }

    /// List all scripts (global + entries + library).
    pub fn list_scripts(&self) -> Vec<Script> {
        let mut out = Vec::new();
        for subdir in &["global", "entries", "library"] {
            let dir = self.base_dir.join(subdir);
            if let Ok(rd) = std::fs::read_dir(&dir) {
                for entry in rd.flatten() {
                    if entry.path().extension().and_then(|e| e.to_str()) == Some("rhai") {
                        if let Some(s) = self.load_script(entry.path()) {
                            out.push(s);
                        }
                    }
                }
            }
        }
        out
    }

    fn load_script(&self, path: PathBuf) -> Option<Script> {
        let content = std::fs::read_to_string(&path).ok()?;
        let name = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("unnamed")
            .to_string();
        Some(Script {
            name,
            path,
            content,
        })
    }

    /// Save (create/overwrite) a script at `entries/<name>.rhai`.
    pub fn save_entry_script(&self, entry_name: &str, content: &str) -> std::io::Result<()> {
        let dir = self.base_dir.join("entries");
        std::fs::create_dir_all(&dir)?;
        std::fs::write(self.entry_script_path(entry_name), content)
    }
}

fn sanitise_name(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '-' || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

// ── ScriptEngine ──────────────────────────────────────────────────────────────

/// Wraps a Rhai [`Engine`] pre-configured with all [`SessionApi`] bindings.
pub struct ScriptEngine {
    engine: Engine,
}

impl ScriptEngine {
    /// Build the engine and register all `SessionApi` methods.
    pub fn new() -> Self {
        let mut engine = Engine::new();

        // Safety: disable file/module access from scripts.
        engine.set_max_operations(1_000_000);

        engine.register_type_with_name::<SessionApi>("Session");

        // s.send(text)
        engine.register_fn("send", |api: &mut SessionApi, text: String| {
            api.do_send(text.into_bytes());
        });

        // s.send_raw(text) — alias for send, treats text as raw bytes
        engine.register_fn("send_raw", |api: &mut SessionApi, text: String| {
            api.do_send(text.into_bytes());
        });

        // s.wait_for(pattern, timeout_secs) → bool
        engine.register_fn(
            "wait_for",
            |api: &mut SessionApi, pattern: String, timeout: f64| -> bool {
                api.do_wait_for(&pattern, timeout)
            },
        );

        // s.wait_ms(ms)
        engine.register_fn("wait_ms", |_api: &mut SessionApi, ms: i64| {
            std::thread::sleep(Duration::from_millis(ms.unsigned_abs()));
        });

        // s.log(message)
        engine.register_fn("log", |api: &mut SessionApi, msg: String| {
            api.do_log(msg);
        });

        // s.notify(message) — writes to log buffer (system notifications Phase 4)
        engine.register_fn("notify", |api: &mut SessionApi, msg: String| {
            api.do_log(format!("[notify] {msg}"));
        });

        // s.set_var(key, val)
        engine.register_fn(
            "set_var",
            |api: &mut SessionApi, key: String, val: String| {
                api.do_set_var(key, val);
            },
        );

        // s.get_var(key) → String
        engine.register_fn("get_var", |api: &mut SessionApi, key: String| -> String {
            api.do_get_var(key)
        });

        // s.entry_name() → String
        engine.register_fn("entry_name", |api: &mut SessionApi| -> String {
            api.do_entry_name()
        });

        // s.disconnect()
        engine.register_fn("disconnect", |api: &mut SessionApi| {
            api.do_disconnect();
        });

        // s.reconnect() — intentionally unavailable until session lifecycle support is added.
        engine.register_fn("reconnect", |api: &mut SessionApi| {
            api.do_log("[reconnect unavailable]".to_string());
        });

        // s.credential(key) → String from the entry's attached credential.
        engine.register_fn(
            "credential",
            |api: &mut SessionApi, key: String| -> String { api.do_credential(key) },
        );

        // Utility: timestamp() global function
        engine.register_fn("timestamp", || -> String {
            chrono::Local::now().format("%H:%M:%S").to_string()
        });

        Self { engine }
    }

    /// Compile a script string into a reusable AST.
    pub fn compile(&self, source: &str) -> Result<AST, String> {
        self.engine.compile(source).map_err(|e| e.to_string())
    }

    /// Call a named hook function in the compiled script.
    ///
    /// Returns `Ok(())` if the function ran successfully *or does not exist*
    /// (absent hooks are silently ignored).
    pub fn run_hook(&self, ast: &AST, fn_name: &str, api: SessionApi) -> Result<(), String> {
        let mut scope = Scope::new();
        let args: Vec<Dynamic> = vec![Dynamic::from(api)];

        match self.engine.call_fn::<()>(&mut scope, ast, fn_name, args) {
            Ok(_) => Ok(()),
            Err(e) if matches!(*e, EvalAltResult::ErrorFunctionNotFound(..)) => Ok(()),
            Err(e) => Err(e.to_string()),
        }
    }

    /// Call `on_data(s, data_str)` — the fast synchronous data hook.
    pub fn run_on_data(&self, ast: &AST, api: SessionApi, data: &str) -> Result<(), String> {
        let mut scope = Scope::new();
        let args: Vec<Dynamic> = vec![Dynamic::from(api), Dynamic::from(data.to_string())];

        match self.engine.call_fn::<()>(&mut scope, ast, "on_data", args) {
            Ok(_) => Ok(()),
            Err(e) if matches!(*e, EvalAltResult::ErrorFunctionNotFound(..)) => Ok(()),
            Err(e) => Err(e.to_string()),
        }
    }
}

impl Default for ScriptEngine {
    fn default() -> Self {
        Self::new()
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::mpsc;

    fn poison_mutex<T>(mutex: Arc<Mutex<T>>)
    where
        T: Send + 'static,
    {
        let _ = std::panic::catch_unwind(move || {
            let _guard = mutex.lock().unwrap();
            panic!("poison mutex");
        });
    }

    fn make_api(
        write_tx: async_mpsc::Sender<Vec<u8>>,
        data_rx: mpsc::Receiver<Vec<u8>>,
    ) -> SessionApi {
        let log_buffer = Arc::new(Mutex::new(Vec::new()));
        SessionApi::new("test-entry".into(), write_tx, data_rx, log_buffer)
    }

    fn make_api_with_credentials(
        write_tx: async_mpsc::Sender<Vec<u8>>,
        data_rx: mpsc::Receiver<Vec<u8>>,
        credentials: HashMap<String, String>,
    ) -> SessionApi {
        let log_buffer = Arc::new(Mutex::new(Vec::new()));
        SessionApi::with_credentials(
            "test-entry".into(),
            write_tx,
            data_rx,
            log_buffer,
            credentials,
        )
    }

    #[test]
    fn compile_valid_script() {
        let engine = ScriptEngine::new();
        assert!(engine.compile("fn on_connect(s) { }").is_ok());
    }

    #[test]
    fn compile_invalid_script() {
        let engine = ScriptEngine::new();
        assert!(engine.compile("fn { INVALID").is_err());
    }

    #[test]
    fn missing_hook_is_ok() {
        let engine = ScriptEngine::new();
        let ast = engine.compile("fn on_connect(s) { }").unwrap();
        let (tx, _rx) = async_mpsc::channel(8);
        let (_dtx, drx) = mpsc::channel();
        let api = make_api(tx, drx);
        // on_disconnect does not exist — should be silently ignored
        assert!(engine.run_hook(&ast, "on_disconnect", api).is_ok());
    }

    #[tokio::test]
    async fn send_delivers_bytes() {
        let engine = ScriptEngine::new();
        let ast = engine
            .compile(r#"fn on_connect(s) { s.send("hello\n"); }"#)
            .unwrap();

        let (tx, mut rx) = async_mpsc::channel(8);
        let (_dtx, drx) = mpsc::channel();
        let api = make_api(tx, drx);

        tokio::task::spawn_blocking(move || engine.run_hook(&ast, "on_connect", api))
            .await
            .unwrap()
            .unwrap();

        let received = rx.recv().await.unwrap();
        assert_eq!(received, b"hello\n");
    }

    #[tokio::test]
    async fn set_and_get_var() {
        let engine = ScriptEngine::new();
        let ast = engine
            .compile(
                r#"fn on_connect(s) { s.set_var("k", "v"); let r = s.get_var("k"); s.send(r); }"#,
            )
            .unwrap();

        let (tx, mut rx) = async_mpsc::channel(8);
        let (_dtx, drx) = mpsc::channel();
        let api = make_api(tx, drx);

        tokio::task::spawn_blocking(move || engine.run_hook(&ast, "on_connect", api))
            .await
            .unwrap()
            .unwrap();

        let received = rx.recv().await.unwrap();
        assert_eq!(received, b"v");
    }

    #[tokio::test]
    async fn entry_name_returns_name() {
        let engine = ScriptEngine::new();
        let ast = engine
            .compile(r#"fn on_connect(s) { s.send(s.entry_name()); }"#)
            .unwrap();

        let (tx, mut rx) = async_mpsc::channel(8);
        let (_dtx, drx) = mpsc::channel();
        let api = make_api(tx, drx);

        tokio::task::spawn_blocking(move || engine.run_hook(&ast, "on_connect", api))
            .await
            .unwrap()
            .unwrap();

        let received = rx.recv().await.unwrap();
        assert_eq!(received, b"test-entry");
    }

    #[tokio::test]
    async fn credential_returns_attached_secret_fields() {
        let engine = ScriptEngine::new();
        let ast = engine
            .compile(
                r#"fn on_connect(s) {
                    s.send(s.credential("username") + ":" + s.credential("password"));
                }"#,
            )
            .unwrap();

        let (tx, mut rx) = async_mpsc::channel(8);
        let (_dtx, drx) = mpsc::channel();
        let credentials = HashMap::from([
            ("username".to_string(), "bbsuser".to_string()),
            ("password".to_string(), "s3cret".to_string()),
        ]);
        let api = make_api_with_credentials(tx, drx, credentials);

        tokio::task::spawn_blocking(move || engine.run_hook(&ast, "on_connect", api))
            .await
            .unwrap()
            .unwrap();

        let received = rx.recv().await.unwrap();
        assert_eq!(received, b"bbsuser:s3cret");
    }

    #[tokio::test]
    async fn credential_missing_key_returns_empty_string() {
        let engine = ScriptEngine::new();
        let ast = engine
            .compile(r#"fn on_connect(s) { s.send("[" + s.credential("missing") + "]"); }"#)
            .unwrap();

        let (tx, mut rx) = async_mpsc::channel(8);
        let (_dtx, drx) = mpsc::channel();
        let credentials = HashMap::from([("username".to_string(), "bbsuser".to_string())]);
        let api = make_api_with_credentials(tx, drx, credentials);

        tokio::task::spawn_blocking(move || engine.run_hook(&ast, "on_connect", api))
            .await
            .unwrap()
            .unwrap();

        let received = rx.recv().await.unwrap();
        assert_eq!(received, b"[]");
    }

    #[tokio::test]
    async fn credential_unavailable_store_returns_empty_string() {
        let engine = ScriptEngine::new();
        let ast = engine
            .compile(r#"fn on_connect(s) { s.send("[" + s.credential("password") + "]"); }"#)
            .unwrap();

        let (tx, mut rx) = async_mpsc::channel(8);
        let (_dtx, drx) = mpsc::channel();
        let api = make_api(tx, drx);

        tokio::task::spawn_blocking(move || engine.run_hook(&ast, "on_connect", api))
            .await
            .unwrap()
            .unwrap();

        let received = rx.recv().await.unwrap();
        assert_eq!(received, b"[]");
    }

    #[tokio::test]
    async fn disconnect_sends_script_command() {
        let engine = ScriptEngine::new();
        let ast = engine
            .compile(r#"fn on_connect(s) { s.disconnect(); }"#)
            .unwrap();

        let (write_tx, _write_rx) = async_mpsc::channel(8);
        let (_data_tx, data_rx) = mpsc::channel();
        let (control_tx, mut control_rx) = async_mpsc::channel(8);
        let log_buffer = Arc::new(Mutex::new(Vec::<String>::new()));
        let api = SessionApi::with_credentials_and_control(
            "test-entry".into(),
            write_tx,
            data_rx,
            log_buffer,
            HashMap::new(),
            control_tx,
        );

        tokio::task::spawn_blocking(move || engine.run_hook(&ast, "on_connect", api))
            .await
            .unwrap()
            .unwrap();

        assert_eq!(control_rx.recv().await, Some(ScriptCommand::Disconnect));
    }

    #[tokio::test]
    async fn reconnect_logs_unavailable_message() {
        let engine = ScriptEngine::new();
        let ast = engine
            .compile(r#"fn on_connect(s) { s.reconnect(); }"#)
            .unwrap();

        let (tx, _rx) = async_mpsc::channel(8);
        let (_dtx, drx) = mpsc::channel();
        let log_buffer = Arc::new(Mutex::new(Vec::<String>::new()));
        let api = SessionApi::new("test-entry".into(), tx, drx, Arc::clone(&log_buffer));

        tokio::task::spawn_blocking(move || engine.run_hook(&ast, "on_connect", api))
            .await
            .unwrap()
            .unwrap();

        assert_eq!(
            log_buffer.lock().unwrap().as_slice(),
            ["[reconnect unavailable]"]
        );
    }

    #[tokio::test]
    async fn wait_for_matches_preloaded_data() {
        let engine = ScriptEngine::new();
        let ast = engine
            .compile(r#"fn on_connect(s) { let ok = s.wait_for("login:", 2.0); s.send(if ok { "matched" } else { "timeout" }); }"#)
            .unwrap();

        let (write_tx, mut write_rx) = async_mpsc::channel(8);
        let (data_tx, data_rx) = mpsc::channel::<Vec<u8>>();
        let log_buffer = Arc::new(Mutex::new(Vec::new()));
        let api = SessionApi::new("test-entry".into(), write_tx, data_rx, log_buffer);

        // Pre-send data that contains "login:" before the script runs.
        data_tx.send(b"Welcome\r\nlogin: ".to_vec()).unwrap();

        tokio::task::spawn_blocking(move || engine.run_hook(&ast, "on_connect", api))
            .await
            .unwrap()
            .unwrap();

        let received = write_rx.recv().await.unwrap();
        assert_eq!(received, b"matched");
    }

    #[tokio::test]
    async fn wait_for_times_out() {
        let engine = ScriptEngine::new();
        let ast = engine
            .compile(r#"fn on_connect(s) { let ok = s.wait_for("never", 0.1); s.send(if ok { "matched" } else { "timeout" }); }"#)
            .unwrap();

        let (write_tx, mut write_rx) = async_mpsc::channel(8);
        let (_data_tx, data_rx) = mpsc::channel::<Vec<u8>>();
        let log_buffer = Arc::new(Mutex::new(Vec::new()));
        let api = SessionApi::new("test-entry".into(), write_tx, data_rx, log_buffer);

        tokio::task::spawn_blocking(move || engine.run_hook(&ast, "on_connect", api))
            .await
            .unwrap()
            .unwrap();

        let received = write_rx.recv().await.unwrap();
        assert_eq!(received, b"timeout");
    }

    #[tokio::test]
    async fn log_messages_collected() {
        let engine = ScriptEngine::new();
        let ast = engine
            .compile(r#"fn on_connect(s) { s.log("step 1"); s.log("step 2"); }"#)
            .unwrap();

        let (tx, _rx) = async_mpsc::channel(8);
        let (_dtx, drx) = mpsc::channel();
        let log_buffer = Arc::new(Mutex::new(Vec::<String>::new()));
        let api = SessionApi::new("test-entry".into(), tx, drx, Arc::clone(&log_buffer));

        tokio::task::spawn_blocking(move || engine.run_hook(&ast, "on_connect", api))
            .await
            .unwrap()
            .unwrap();

        let msgs = log_buffer.lock().unwrap().clone();
        assert_eq!(msgs, vec!["step 1", "step 2"]);
    }

    #[tokio::test]
    async fn script_state_lock_poisoning_does_not_panic() {
        let engine = ScriptEngine::new();
        let ast = engine
            .compile(
                r#"fn on_connect(s) {
                    s.set_var("k", "v");
                    s.log("step");
                    s.notify("note");
                    s.send(s.get_var("k") + "|" + s.entry_name());
                }"#,
            )
            .unwrap();

        let (tx, mut rx) = async_mpsc::channel(8);
        let (_dtx, drx) = mpsc::channel();
        let api = make_api(tx, drx);
        poison_mutex(Arc::clone(&api.inner));

        tokio::task::spawn_blocking(move || engine.run_hook(&ast, "on_connect", api))
            .await
            .unwrap()
            .unwrap();

        let received = rx.recv().await.unwrap();
        assert_eq!(received, b"|");
    }

    #[tokio::test]
    async fn script_log_buffer_lock_poisoning_does_not_panic() {
        let engine = ScriptEngine::new();
        let ast = engine
            .compile(r#"fn on_connect(s) { s.log("step"); s.notify("note"); s.send("done"); }"#)
            .unwrap();

        let (tx, mut rx) = async_mpsc::channel(8);
        let (_dtx, drx) = mpsc::channel();
        let log_buffer = Arc::new(Mutex::new(Vec::<String>::new()));
        let api = SessionApi::new("test-entry".into(), tx, drx, Arc::clone(&log_buffer));
        poison_mutex(log_buffer);

        tokio::task::spawn_blocking(move || engine.run_hook(&ast, "on_connect", api))
            .await
            .unwrap()
            .unwrap();

        let received = rx.recv().await.unwrap();
        assert_eq!(received, b"done");
    }

    #[tokio::test]
    async fn wait_for_returns_false_when_data_lock_is_poisoned() {
        let engine = ScriptEngine::new();
        let ast = engine
            .compile(r#"fn on_connect(s) { s.send(if s.wait_for("login:", 0.1) { "matched" } else { "failed" }); }"#)
            .unwrap();

        let (tx, mut rx) = async_mpsc::channel(8);
        let (_dtx, drx) = mpsc::channel();
        let api = make_api(tx, drx);
        poison_mutex(Arc::clone(&api.data_rx));

        tokio::task::spawn_blocking(move || engine.run_hook(&ast, "on_connect", api))
            .await
            .unwrap()
            .unwrap();

        let received = rx.recv().await.unwrap();
        assert_eq!(received, b"failed");
    }

    #[test]
    fn on_data_hook_fires() {
        let engine = ScriptEngine::new();
        let ast = engine
            .compile(r#"fn on_data(s, data) { s.send(data); }"#)
            .unwrap();

        let (tx, _rx) = async_mpsc::channel(8);
        let (_dtx, drx) = mpsc::channel();
        let api = make_api(tx, drx);

        assert!(engine.run_on_data(&ast, api, "hello from remote").is_ok());
    }

    #[test]
    fn script_store_save_and_load() {
        let dir = tempfile::tempdir().unwrap();
        let store = ScriptStore::new(dir.path());
        let content = r#"fn on_connect(s) { s.send("hi"); }"#;
        store.save_entry_script("my-server", content).unwrap();
        let script = store.entry_script("my-server").unwrap();
        assert_eq!(script.content, content);
        assert_eq!(script.name, "my-server");
    }

    #[test]
    fn named_script_searches_script_store_directories() {
        let dir = tempfile::tempdir().unwrap();
        let store = ScriptStore::new(dir.path());
        let global_dir = dir.path().join("global");
        std::fs::create_dir_all(&global_dir).unwrap();
        std::fs::write(global_dir.join("dial.rhai"), "fn on_connect(s) { }").unwrap();

        let script = store.named_script("dial").unwrap();

        assert_eq!(script.name, "dial");
        assert_eq!(script.path, global_dir.join("dial.rhai"));
    }

    #[test]
    fn named_script_sanitises_requested_name() {
        let dir = tempfile::tempdir().unwrap();
        let store = ScriptStore::new(dir.path());
        let entries_dir = dir.path().join("entries");
        std::fs::create_dir_all(&entries_dir).unwrap();
        std::fs::write(entries_dir.join("bbs_login.rhai"), "fn on_connect(s) { }").unwrap();

        let script = store.named_script("bbs login").unwrap();

        assert_eq!(script.path, entries_dir.join("bbs_login.rhai"));
    }
}
