/// VT100/ANSI terminal state machine — implements `vte::Perform`.
///
/// This struct holds all mutable terminal state (grid, cursor, SGR, scroll
/// region). It is driven by `vte::Parser::advance` byte-by-byte.
/// `TerminalEmulator` owns both the parser and this state.
use vte::{Params, Perform};

use super::cell::{Cell, CellStyle, Color};

// ── Saved cursor ──────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Default)]
struct SavedCursor {
    col: u16,
    row: u16,
    style: CellStyle,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
enum Charset {
    #[default]
    Ascii,
    DecSpecialGraphics,
}

// ── Terminal state ────────────────────────────────────────────────────────────

pub struct TerminalState {
    pub cols: u16,
    pub rows: u16,
    /// Row-major grid: `grid[row][col]`.
    pub grid: Vec<Vec<Cell>>,
    pub cursor_col: u16,
    pub cursor_row: u16,
    pub cursor_visible: bool,
    /// Current SGR style applied to newly written characters.
    pub current_style: CellStyle,
    /// Saved cursor for ESC 7 / ESC 8 / CSI s/u (DECSC/DECRC).
    saved_cursor: SavedCursor,
    /// Top row of scrolling region (0-based, inclusive).
    scroll_top: u16,
    /// Bottom row of scrolling region (0-based, inclusive).
    scroll_bottom: u16,
    /// Tab stop positions.
    tab_stops: Vec<bool>,
    /// Pending-wrap: cursor is at col == cols, next char wraps to next line.
    pending_wrap: bool,
    /// DEC auto-wrap mode (DECAWM ?7), enabled by default on ANSI/VT terminals.
    auto_wrap: bool,

    // ── Alternate screen buffer ───────────────────────────────────────────────
    /// True when the alternate screen is active.
    pub in_alt_screen: bool,
    /// The screen NOT currently active (swapped in/out by ?47/?1049).
    alt_grid: Vec<Vec<Cell>>,
    alt_cursor_col: u16,
    alt_cursor_row: u16,
    alt_cursor_visible: bool,

    // ── Window title (set by OSC 0 / OSC 2) ──────────────────────────────────
    pub title: Option<String>,

    // ── Application cursor keys mode (DECCKM ?1h/l) ───────────────────────────
    pub app_cursor_keys: bool,

    /// Bytes generated by terminal reports that must be sent back upstream.
    pending_output: Vec<u8>,

    /// VT100 G0/G1 character sets used by DEC line-drawing mode.
    g0_charset: Charset,
    g1_charset: Charset,
    active_charset: Charset,
}

impl TerminalState {
    pub fn new(cols: u16, rows: u16) -> Self {
        let mut tab_stops = vec![false; cols as usize];
        for i in (0..cols as usize).step_by(8) {
            tab_stops[i] = true;
        }
        Self {
            cols,
            rows,
            grid: vec![vec![Cell::default(); cols as usize]; rows as usize],
            cursor_col: 0,
            cursor_row: 0,
            cursor_visible: true,
            current_style: CellStyle::default(),
            saved_cursor: SavedCursor::default(),
            scroll_top: 0,
            scroll_bottom: rows.saturating_sub(1),
            tab_stops,
            pending_wrap: false,
            auto_wrap: true,
            in_alt_screen: false,
            alt_grid: vec![vec![Cell::default(); cols as usize]; rows as usize],
            alt_cursor_col: 0,
            alt_cursor_row: 0,
            alt_cursor_visible: true,
            title: None,
            app_cursor_keys: false,
            pending_output: Vec::new(),
            g0_charset: Charset::Ascii,
            g1_charset: Charset::Ascii,
            active_charset: Charset::Ascii,
        }
    }

    pub fn take_output(&mut self) -> Vec<u8> {
        std::mem::take(&mut self.pending_output)
    }

    pub fn resize(&mut self, cols: u16, rows: u16) {
        // Adjust each row
        for row in &mut self.grid {
            row.resize(cols as usize, Cell::default());
        }
        // Adjust number of rows
        self.grid
            .resize(rows as usize, vec![Cell::default(); cols as usize]);

        self.cols = cols;
        self.rows = rows;
        self.scroll_top = 0;
        self.scroll_bottom = rows.saturating_sub(1);
        self.cursor_col = self.cursor_col.min(cols.saturating_sub(1));
        self.cursor_row = self.cursor_row.min(rows.saturating_sub(1));

        // Also resize alt grid
        for row in &mut self.alt_grid {
            row.resize(cols as usize, Cell::default());
        }
        self.alt_grid
            .resize(rows as usize, vec![Cell::default(); cols as usize]);
        self.alt_cursor_col = self.alt_cursor_col.min(cols.saturating_sub(1));
        self.alt_cursor_row = self.alt_cursor_row.min(rows.saturating_sub(1));

        // Rebuild tab stops
        self.tab_stops = vec![false; cols as usize];
        for i in (0..cols as usize).step_by(8) {
            self.tab_stops[i] = true;
        }
    }

    // ── Grid helpers ──────────────────────────────────────────────────────────

    fn cell_mut(&mut self, col: u16, row: u16) -> Option<&mut Cell> {
        self.grid
            .get_mut(row as usize)
            .and_then(|r| r.get_mut(col as usize))
    }

    /// A blank (space) cell with only the current background color preserved.
    /// Used by erase operations — foreground and attributes are reset per spec.
    fn blank_cell(&self) -> Cell {
        Cell {
            ch: ' ',
            style: CellStyle {
                bg: self.current_style.bg.clone(),
                ..CellStyle::default()
            },
        }
    }

    /// Write a character at the current cursor position and advance.
    fn put_char(&mut self, ch: char) {
        if self.pending_wrap {
            self.cursor_col = 0;
            self.advance_row();
            self.pending_wrap = false;
        }

        let col = self.cursor_col;
        let row = self.cursor_row;
        let style = self.current_style.clone();

        if let Some(cell) = self.cell_mut(col, row) {
            cell.ch = ch;
            cell.style = style;
        }

        if self.cursor_col + 1 >= self.cols {
            if !self.auto_wrap {
                return;
            }
            self.pending_wrap = true;
        } else {
            self.cursor_col += 1;
        }
    }

    /// Move cursor down one row, scrolling if at the scroll-region bottom.
    fn advance_row(&mut self) {
        if self.cursor_row == self.scroll_bottom {
            self.scroll_up(1);
        } else if self.cursor_row + 1 < self.rows {
            self.cursor_row += 1;
        }
    }

    /// Scroll the scroll region up by `count` lines (new blank lines at bottom).
    fn scroll_up(&mut self, count: u16) {
        let top = self.scroll_top as usize;
        let bottom = self.scroll_bottom as usize;
        let count = count as usize;
        let count = count.min(bottom - top + 1);
        let blank = self.blank_cell();

        for _ in 0..count {
            self.grid.remove(top);
            self.grid
                .insert(bottom, vec![blank.clone(); self.cols as usize]);
        }
    }

    /// Scroll the scroll region down by `count` lines (new blank lines at top).
    fn scroll_down(&mut self, count: u16) {
        let top = self.scroll_top as usize;
        let bottom = self.scroll_bottom as usize;
        let count = count as usize;
        let count = count.min(bottom - top + 1);
        let blank = self.blank_cell();

        for _ in 0..count {
            if bottom < self.grid.len() {
                self.grid.remove(bottom);
            }
            self.grid
                .insert(top, vec![blank.clone(); self.cols as usize]);
        }
    }

    // ── Cursor movement ───────────────────────────────────────────────────────

    fn cursor_up(&mut self, n: u16) {
        self.pending_wrap = false;
        self.cursor_row = self.cursor_row.saturating_sub(n).max(self.scroll_top);
    }

    fn cursor_down(&mut self, n: u16) {
        self.pending_wrap = false;
        self.cursor_row = (self.cursor_row + n).min(self.scroll_bottom);
    }

    fn cursor_forward(&mut self, n: u16) {
        self.pending_wrap = false;
        self.cursor_col = (self.cursor_col + n).min(self.cols.saturating_sub(1));
    }

    fn cursor_back(&mut self, n: u16) {
        self.pending_wrap = false;
        self.cursor_col = self.cursor_col.saturating_sub(n);
    }

    fn cursor_goto(&mut self, col: u16, row: u16) {
        self.pending_wrap = false;
        self.cursor_col = col.min(self.cols.saturating_sub(1));
        self.cursor_row = row.min(self.rows.saturating_sub(1));
    }

    // ── Erase operations ──────────────────────────────────────────────────────

    /// ED — Erase In Display
    fn erase_display(&mut self, mode: u16) {
        let col = self.cursor_col as usize;
        let row = self.cursor_row as usize;
        let cols = self.cols as usize;
        let rows = self.rows as usize;
        let blank = self.blank_cell();

        match mode {
            0 => {
                // Below cursor (inclusive)
                for c in col..cols {
                    self.grid[row][c] = blank.clone();
                }
                for r in (row + 1)..rows {
                    self.grid[r] = vec![blank.clone(); cols];
                }
            }
            1 => {
                // Above cursor (inclusive)
                for r in 0..row {
                    self.grid[r] = vec![blank.clone(); cols];
                }
                for c in 0..=col {
                    self.grid[row][c] = blank.clone();
                }
            }
            2 | 3 => {
                // Entire screen
                for r in 0..rows {
                    self.grid[r] = vec![blank.clone(); cols];
                }
            }
            _ => {}
        }
    }

    /// EL — Erase In Line
    fn erase_line(&mut self, mode: u16) {
        let col = self.cursor_col as usize;
        let row = self.cursor_row as usize;
        let cols = self.cols as usize;
        let blank = self.blank_cell();

        match mode {
            0 => {
                // Right of cursor (inclusive)
                for c in col..cols {
                    self.grid[row][c] = blank.clone();
                }
            }
            1 => {
                // Left of cursor (inclusive)
                for c in 0..=col.min(cols.saturating_sub(1)) {
                    self.grid[row][c] = blank.clone();
                }
            }
            2 => {
                // Entire line
                self.grid[row] = vec![blank; cols];
            }
            _ => {}
        }
    }

    /// IL — Insert Lines
    fn insert_lines(&mut self, n: u16) {
        let row = self.cursor_row as usize;
        let bottom = self.scroll_bottom as usize;
        let cols = self.cols as usize;
        let n = n as usize;
        let blank = self.blank_cell();

        for _ in 0..n {
            if bottom < self.grid.len() {
                self.grid.remove(bottom);
            }
            self.grid.insert(row, vec![blank.clone(); cols]);
        }
    }

    /// DL — Delete Lines
    fn delete_lines(&mut self, n: u16) {
        let row = self.cursor_row as usize;
        let bottom = self.scroll_bottom as usize;
        let cols = self.cols as usize;
        let n = n as usize;
        let blank = self.blank_cell();

        for _ in 0..n {
            if row < self.grid.len() {
                self.grid.remove(row);
            }
            self.grid.insert(bottom, vec![blank.clone(); cols]);
        }
    }

    /// DCH — Delete Characters
    fn delete_chars(&mut self, n: u16) {
        let col = self.cursor_col as usize;
        let row = self.cursor_row as usize;
        let cols = self.cols as usize;
        let n = n as usize;
        let blank = self.blank_cell();

        let end = cols.min(col + n);
        self.grid[row].drain(col..end);
        let to_add = end - col;
        self.grid[row].resize(cols, blank);
        // Re-pad so length stays cols
        let _ = to_add; // used implicitly via resize
    }

    // ── Alternate screen buffer ───────────────────────────────────────────────

    /// Enter the alternate screen.  If `save_cursor` is true, the current
    /// cursor + style is saved (DECSC) before switching.
    pub fn enter_alt_screen(&mut self, save_cursor: bool) {
        if self.in_alt_screen {
            return;
        }
        if save_cursor {
            self.saved_cursor = SavedCursor {
                col: self.cursor_col,
                row: self.cursor_row,
                style: self.current_style.clone(),
            };
        }
        // Swap grids and cursor state so all existing operations hit alt screen.
        std::mem::swap(&mut self.grid, &mut self.alt_grid);
        std::mem::swap(&mut self.cursor_col, &mut self.alt_cursor_col);
        std::mem::swap(&mut self.cursor_row, &mut self.alt_cursor_row);
        std::mem::swap(&mut self.cursor_visible, &mut self.alt_cursor_visible);
        // Clear the now-active grid (fresh alt screen).
        let cols = self.cols as usize;
        let rows = self.rows as usize;
        for r in 0..rows {
            self.grid[r] = vec![Cell::default(); cols];
        }
        self.cursor_col = 0;
        self.cursor_row = 0;
        self.pending_wrap = false;
        self.in_alt_screen = true;
    }

    /// Leave the alternate screen.  If `restore_cursor` is true, the saved
    /// cursor (from `enter_alt_screen(true)`) is restored.
    pub fn leave_alt_screen(&mut self, restore_cursor: bool) {
        if !self.in_alt_screen {
            return;
        }
        std::mem::swap(&mut self.grid, &mut self.alt_grid);
        std::mem::swap(&mut self.cursor_col, &mut self.alt_cursor_col);
        std::mem::swap(&mut self.cursor_row, &mut self.alt_cursor_row);
        std::mem::swap(&mut self.cursor_visible, &mut self.alt_cursor_visible);
        if restore_cursor {
            let saved = self.saved_cursor.clone();
            self.cursor_col = saved.col;
            self.cursor_row = saved.row;
            self.current_style = saved.style;
        }
        self.pending_wrap = false;
        self.in_alt_screen = false;
    }

    // ── Insert / Erase characters ─────────────────────────────────────────────

    /// ICH — Insert Character: insert `n` blank chars at cursor, shifting right.
    fn insert_chars(&mut self, n: u16) {
        let col = self.cursor_col as usize;
        let row = self.cursor_row as usize;
        let cols = self.cols as usize;
        let n = (n as usize).min(cols - col);
        let row_cells = &mut self.grid[row];
        row_cells.truncate(cols - n);
        for _ in 0..n {
            row_cells.insert(col, Cell::default());
        }
    }

    /// ECH — Erase Character: overwrite `n` chars at cursor with blanks.
    fn erase_chars(&mut self, n: u16) {
        let col = self.cursor_col as usize;
        let row = self.cursor_row as usize;
        let cols = self.cols as usize;
        let end = (col + n as usize).min(cols);
        for c in col..end {
            self.grid[row][c] = Cell::default();
        }
    }

    // ── SGR — Select Graphic Rendition ───────────────────────────────────────

    fn apply_sgr(&mut self, params: &Params) {
        let mut iter = params.iter();

        while let Some(param) = iter.next() {
            // vte gives each param as a slice (for sub-params); take first element
            let p = param.first().copied().unwrap_or(0);

            match p {
                0 => self.current_style = CellStyle::default(),
                1 => self.current_style.bold = true,
                2 => self.current_style.dim = true,
                3 => self.current_style.italic = true,
                4 => self.current_style.underline = true,
                5 | 6 => self.current_style.blink = true,
                7 => self.current_style.reverse = true,
                8 => self.current_style.invisible = true,
                9 => self.current_style.strikethrough = true,
                22 => {
                    self.current_style.bold = false;
                    self.current_style.dim = false;
                }
                23 => self.current_style.italic = false,
                24 => self.current_style.underline = false,
                25 => self.current_style.blink = false,
                27 => self.current_style.reverse = false,
                28 => self.current_style.invisible = false,
                29 => self.current_style.strikethrough = false,
                // 8-color foreground (30–37), bright fg (90–97)
                30..=37 => self.current_style.fg = Color::Ansi(p as u8 - 30),
                39 => self.current_style.fg = Color::Default,
                // 8-color background (40–47), bright bg (100–107)
                40..=47 => self.current_style.bg = Color::Ansi(p as u8 - 40),
                49 => self.current_style.bg = Color::Default,
                // Bright foreground (90–97)
                90..=97 => self.current_style.fg = Color::Ansi(p as u8 - 90 + 8),
                // Bright background (100–107)
                100..=107 => self.current_style.bg = Color::Ansi(p as u8 - 100 + 8),
                // 256-color / true-color: 38 and 48 take sub-params
                38 | 48 => {
                    // Peek at next param to determine mode
                    let Some(next_param) = iter.next() else {
                        break;
                    };
                    let mode = next_param.first().copied().unwrap_or(0);
                    let color = match mode {
                        5 => {
                            // 256-color: 38;5;n
                            let Some(idx_param) = iter.next() else { break };
                            let idx = idx_param.first().copied().unwrap_or(0);
                            Color::Palette(idx as u8)
                        }
                        2 => {
                            // True-color: 38;2;r;g;b
                            let r = iter.next().and_then(|p| p.first().copied()).unwrap_or(0) as u8;
                            let g = iter.next().and_then(|p| p.first().copied()).unwrap_or(0) as u8;
                            let b = iter.next().and_then(|p| p.first().copied()).unwrap_or(0) as u8;
                            Color::Rgb(r, g, b)
                        }
                        _ => break,
                    };
                    if p == 38 {
                        self.current_style.fg = color;
                    } else {
                        self.current_style.bg = color;
                    }
                }
                _ => {} // Unrecognised SGR code — ignore
            }
        }
    }
}

// ── vte::Perform implementation ───────────────────────────────────────────────

impl Perform for TerminalState {
    /// Printable character — place on screen and advance cursor.
    fn print(&mut self, c: char) {
        self.put_char(map_charset_char(self.active_charset, c));
    }

    /// C0/C1 control characters.
    fn execute(&mut self, byte: u8) {
        match byte {
            0x07 => {} // BEL — ignore (no audio in Phase 1)
            0x08 => {
                // BS — backspace
                self.pending_wrap = false;
                self.cursor_col = self.cursor_col.saturating_sub(1);
            }
            0x09 => {
                // HT — horizontal tab to next tab stop
                self.pending_wrap = false;
                let start = (self.cursor_col + 1) as usize;
                let stops = &self.tab_stops;
                let next = (start..stops.len())
                    .find(|&i| stops[i])
                    .unwrap_or(self.cols as usize - 1);
                self.cursor_col = (next as u16).min(self.cols - 1);
            }
            0x0A..=0x0C => {
                // LF / VT / FF — line feed
                self.advance_row();
                self.pending_wrap = false;
            }
            0x0D => {
                // CR — carriage return
                self.cursor_col = 0;
                self.pending_wrap = false;
            }
            0x0E => {
                // SO — shift out, select G1
                self.active_charset = self.g1_charset;
            }
            0x0F => {
                // SI — shift in, select G0
                self.active_charset = self.g0_charset;
            }
            _ => {} // Other C0 bytes ignored in Phase 1
        }
    }

    /// CSI sequences — the bulk of VT100/ANSI.
    fn csi_dispatch(&mut self, params: &Params, intermediates: &[u8], _ignore: bool, action: char) {
        // Helper: get 1-based param, defaulting to `def`, converted to 0-based
        let p = |params: &Params, idx: usize, def: u16| -> u16 {
            params
                .iter()
                .nth(idx)
                .and_then(|p| p.first().copied())
                .map(|v| if v == 0 { def } else { v })
                .unwrap_or(def)
        };

        // Private sequences use '?' intermediate
        let private = intermediates.first() == Some(&b'?');

        match (action, private) {
            // ── Cursor movement ───────────────────────────────────────────────
            ('A', _) => self.cursor_up(p(params, 0, 1)),
            ('B', _) => self.cursor_down(p(params, 0, 1)),
            ('C', _) => self.cursor_forward(p(params, 0, 1)),
            ('D', _) => self.cursor_back(p(params, 0, 1)),
            ('E', _) => {
                // CNL — next line
                let n = p(params, 0, 1);
                self.cursor_down(n);
                self.cursor_col = 0;
            }
            ('F', _) => {
                // CPL — previous line
                let n = p(params, 0, 1);
                self.cursor_up(n);
                self.cursor_col = 0;
            }
            ('G', _) => {
                // CHA — cursor horizontal absolute (1-based → 0-based)
                self.cursor_col = p(params, 0, 1).saturating_sub(1);
            }
            ('H', _) | ('f', _) => {
                // CUP / HVP — cursor position (row, col; 1-based)
                let row = p(params, 0, 1).saturating_sub(1);
                let col = p(params, 1, 1).saturating_sub(1);
                self.cursor_goto(col, row);
            }
            ('d', _) => {
                // VPA — vertical position absolute (1-based)
                let row = p(params, 0, 1).saturating_sub(1);
                self.cursor_row = row.min(self.rows.saturating_sub(1));
            }

            // ── Erase ─────────────────────────────────────────────────────────
            ('J', _) => self.erase_display(p(params, 0, 0)),
            ('K', _) => self.erase_line(p(params, 0, 0)),

            // ── Insert / Delete / Erase characters ───────────────────────────
            ('@', _) => self.insert_chars(p(params, 0, 1)), // ICH
            ('X', _) => self.erase_chars(p(params, 0, 1)),  // ECH

            // ── Insert / Delete lines ─────────────────────────────────────────
            ('L', _) => self.insert_lines(p(params, 0, 1)),
            ('M', _) => self.delete_lines(p(params, 0, 1)),
            ('P', _) => self.delete_chars(p(params, 0, 1)),

            // ── Scroll ────────────────────────────────────────────────────────
            ('S', _) => self.scroll_up(p(params, 0, 1)),
            ('T', _) => self.scroll_down(p(params, 0, 1)),

            // ── SGR ───────────────────────────────────────────────────────────
            ('m', _) => self.apply_sgr(params),

            // ── Device status reports ─────────────────────────────────────────
            ('n', _) => match p(params, 0, 0) {
                5 => self.pending_output.extend_from_slice(b"\x1b[0n"),
                6 => {
                    let response = format!("\x1b[{};{}R", self.cursor_row + 1, self.cursor_col + 1);
                    self.pending_output.extend_from_slice(response.as_bytes());
                }
                _ => {}
            },

            // ── Scrolling region ──────────────────────────────────────────────
            ('r', _) => {
                // DECSTBM — Set Top and Bottom Margins (1-based)
                let top = p(params, 0, 1).saturating_sub(1);
                let bottom = p(params, 1, self.rows)
                    .saturating_sub(1)
                    .min(self.rows.saturating_sub(1));
                if top < bottom {
                    self.scroll_top = top;
                    self.scroll_bottom = bottom;
                    self.cursor_goto(0, 0);
                }
            }

            // ── Save / Restore cursor ─────────────────────────────────────────
            ('s', _) => {
                self.saved_cursor = SavedCursor {
                    col: self.cursor_col,
                    row: self.cursor_row,
                    style: self.current_style.clone(),
                };
            }
            ('u', _) => {
                let saved = self.saved_cursor.clone();
                self.cursor_col = saved.col;
                self.cursor_row = saved.row;
                self.current_style = saved.style;
                self.pending_wrap = false;
            }

            // ── DEC private modes ─────────────────────────────────────────────
            ('h', true) => {
                for param in params.iter() {
                    match param.first().copied().unwrap_or(0) {
                        1 => self.app_cursor_keys = true,    // DECCKM
                        7 => self.auto_wrap = true,          // DECAWM on
                        25 => self.cursor_visible = true,    // DECTCEM show
                        47 => self.enter_alt_screen(false),  // alt screen
                        1049 => self.enter_alt_screen(true), // alt screen + save cursor
                        2004 => {}                           // bracketed paste — no-op
                        _ => {}
                    }
                }
            }
            ('l', true) => {
                for param in params.iter() {
                    match param.first().copied().unwrap_or(0) {
                        1 => self.app_cursor_keys = false, // DECCKM
                        7 => {
                            self.auto_wrap = false; // DECAWM off
                            self.pending_wrap = false;
                        }
                        25 => self.cursor_visible = false, // DECTCEM hide
                        47 => self.leave_alt_screen(false), // alt screen exit
                        1049 => self.leave_alt_screen(true), // alt screen exit + restore
                        2004 => {}                         // bracketed paste — no-op
                        _ => {}
                    }
                }
            }

            // ── Tab ───────────────────────────────────────────────────────────
            ('I', _) => {
                // CHT — cursor forward tabulation
                let n = p(params, 0, 1);
                for _ in 0..n {
                    self.execute(0x09);
                }
            }
            ('Z', _) => {
                // CBT — cursor backward tabulation
                let n = p(params, 0, 1) as usize;
                let col = self.cursor_col as usize;
                let found = (0..col).rev().filter(|&i| self.tab_stops[i]).nth(n - 1);
                self.cursor_col = found.unwrap_or(0) as u16;
            }

            _ => {} // Unknown CSI — ignore
        }
    }

    /// ESC sequences.
    fn esc_dispatch(&mut self, intermediates: &[u8], _ignore: bool, byte: u8) {
        match (intermediates.first(), byte) {
            (None, b'7') => {
                // DECSC — save cursor
                self.saved_cursor = SavedCursor {
                    col: self.cursor_col,
                    row: self.cursor_row,
                    style: self.current_style.clone(),
                };
            }
            (None, b'8') => {
                // DECRC — restore cursor
                let saved = self.saved_cursor.clone();
                self.cursor_col = saved.col;
                self.cursor_row = saved.row;
                self.current_style = saved.style;
                self.pending_wrap = false;
            }
            (None, b'M') => {
                // RI — reverse index (scroll down if at top of scroll region)
                if self.cursor_row == self.scroll_top {
                    self.scroll_down(1);
                } else {
                    self.cursor_row = self.cursor_row.saturating_sub(1);
                }
            }
            (None, b'c') => {
                // RIS — full reset
                *self = Self::new(self.cols, self.rows);
            }
            (None, b'D') => {
                // IND — Index (LF without CR)
                self.advance_row();
            }
            (None, b'E') => {
                // NEL — next line
                self.cursor_col = 0;
                self.advance_row();
            }
            (Some(b'('), byte) => {
                self.g0_charset = charset_from_designator(byte);
                self.active_charset = self.g0_charset;
            }
            (Some(b')'), byte) => {
                self.g1_charset = charset_from_designator(byte);
            }
            _ => {}
        }
    }

    fn osc_dispatch(&mut self, params: &[&[u8]], _bell_terminated: bool) {
        // OSC 0 and OSC 2: set window/icon title
        if params.len() >= 2 && (params[0] == b"0" || params[0] == b"2") {
            if let Ok(s) = std::str::from_utf8(params[1]) {
                self.title = Some(s.to_string());
            }
        }
    }
    fn hook(&mut self, _params: &Params, _intermediates: &[u8], _ignore: bool, _action: char) {}
    fn put(&mut self, _byte: u8) {}
    fn unhook(&mut self) {}
}

fn charset_from_designator(byte: u8) -> Charset {
    match byte {
        b'0' => Charset::DecSpecialGraphics,
        _ => Charset::Ascii,
    }
}

fn map_charset_char(charset: Charset, c: char) -> char {
    if charset != Charset::DecSpecialGraphics {
        return c;
    }

    match c {
        '`' => '◆',
        'a' => '▒',
        'f' => '°',
        'g' => '±',
        'j' => '┘',
        'k' => '┐',
        'l' => '┌',
        'm' => '└',
        'n' => '┼',
        'o' => '⎺',
        'p' => '⎻',
        'q' => '─',
        'r' => '⎼',
        's' => '⎽',
        't' => '├',
        'u' => '┤',
        'v' => '┴',
        'w' => '┬',
        'x' => '│',
        'y' => '≤',
        'z' => '≥',
        '{' => 'π',
        '|' => '≠',
        '}' => '£',
        '~' => '·',
        _ => c,
    }
}
